### ISSUE TITLE
Add autodiscovery

### ISSUE THREAD

**Issue by Konafets** [nWidart/Laravel-broadway#22]
Since versio 5.5 Laravel is able to discover the ServiceProviders by itself with a little bit of code in composer.json. If the user does not need all SP he can add a statement in the projects composer.json. The whole thing is described here https://medium.com/@taylorotwell/package-auto-discovery-in-laravel-5-5-ea9e3ab20518

If you like this, I would create a PR.

**Comment by Lavoaster** [comment]
Sure, go ahead and submit a PR :)

**Comment by Lavoaster** [comment]
Just an FYI - Laravel 5.5 requries PHPUnit 6 which causes some major conflicts with Broadway as it uses PHPUnit 5.

**Comment by Konafets** [comment]
There is a PR for PHPUnit 6 https://github.com/broadway/broadway/pull/331
