### ISSUE TITLE
Call to undefined method Nwidart\LaravelBroadway\LaravelBroadwayServiceProvider::mergeConfigFrom()

### ISSUE THREAD

**Issue by alessione78** [nWidart/Laravel-broadway#4]
Hi, I'm trying to use your package within my laravel project. When I run composer install it returns an error (in the title of the issue).

I'm using laravel 4.2 and I required version 0.2 of your repo. Unfortunatelly the method mergeConfigFrom is available in laravel 5 but not in 4.2.
Con you be so kind to fix this? Thanks.

**Comment by nWidart** [comment]
Hello,

You can use version `~0.2` on laravel `4.x`
